# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Conf_Mgmt.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtSql import QSqlDatabase, QSqlTableModel, QSqlQueryModel


db = QSqlDatabase.addDatabase("QPSQL")
db.setDatabaseName("nfl")
db.setHostName("localhost")
#db.setUserName("timvannaman")
db.setUserName("pynfl")
db.setPassword("pynfl")
db.open()


class Ui_Conf_Mgmt(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(413, 353)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.model = QSqlTableModel(db=db)
        self.tableView.setModel(self.model)
        self.model.setTable("conference")
        self.model.setHeaderData(0,Qt.Horizontal,"Conf ID")
        self.model.setHeaderData(1,Qt.Horizontal,"Conf Name")
        self.model.select()
        self.tableView.setGeometry(QtCore.QRect(10, 50, 391, 201))
        self.tableView.setObjectName("tableView")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 411, 31))
        self.label.setObjectName("label")
        self.SaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveButton.setGeometry(QtCore.QRect(140, 300, 153, 38))
        self.SaveButton.clicked.connect(self.commit_tx)
        font = QtGui.QFont()
        self.model.setEditStrategy(QSqlTableModel.OnManualSubmit)
        self.tableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableView.resizeColumnToContents(0)
        self.tableView.resizeColumnToContents(1)

        font.setFamily("Book Antiqua")
        font.setPointSize(14)
        self.SaveButton.setFont(font)
        self.SaveButton.setObjectName("SaveButton")
        self.AddConfButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddConfButton.setGeometry(QtCore.QRect(60, 260, 140, 33))
        self.AddConfButton.clicked.connect(self.add_row)
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(14)
        self.AddConfButton.setFont(font)
        self.AddConfButton.setObjectName("AddConfButton")
        self.DelConfButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(14)
        self.DelConfButton.setFont(font)
        self.DelConfButton.setObjectName("DelConfButton")
        self.DelConfButton.setGeometry(QtCore.QRect(210, 260, 140, 33))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def commit_tx(self):
        submit = self.model.submitAll()

    def add_row(self):
        row = self.model.rowCount()
        record = self.model.record()
        #record.setGenerated('team_id', False)    # primary key
        self.model.insertRecord(row, record)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">Conference Management</span></p></body></html>"))
        self.SaveButton.setText(_translate("MainWindow", "Save Changes"))
        self.AddConfButton.setText(_translate("MainWindow", "Add Conference"))
        self.DelConfButton.setText(_translate("MainWindow", "Delete Conference"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Conf_Mgmt()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
