# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_roster.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from itertools import chain
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import Qt

from myconn import connect_to_mysql
import mysql.connector
from login import get_db_config


class Ui_view_roster(object):
    def setupUi(self, view_roster):
        view_roster.setObjectName("view_roster")
        view_roster.resize(800, 601)
        self.centralwidget = QtWidgets.QWidget(view_roster)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tbl_team = QtWidgets.QTableWidget(self.centralwidget)
        self.tbl_team.setObjectName("tbl_team")
        self.tbl_team.setColumnCount(12)
        self.tbl_team.setRowCount(0)
        self.verticalLayout.addWidget(self.tbl_team)
        self.cb_selteam = QtWidgets.QComboBox(self.centralwidget)
        self.cb_selteam.setObjectName("cb_selteam")
        self.verticalLayout.addWidget(self.cb_selteam)
        self.loadButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadButton.setObjectName("loadButton")
        self.verticalLayout.addWidget(self.loadButton)
        view_roster.setCentralWidget(self.centralwidget)
        self.loadButton.clicked.connect(self.loadteam)
        labels = ["No.","Name","Pos","Ht","Wt","Yrs","Spd","Run","Rcv","Blk","Pass","Kick"]
        self.tbl_team.setHorizontalHeaderLabels(labels)
        #header.setSectionResizeMode(12,QtWidgets.QHeaderView.ResizeToContents)
        

        self.retranslateUi(view_roster)
        QtCore.QMetaObject.connectSlotsByName(view_roster)

        # Connect to DB and load teams into combobox
        config = get_db_config()
        conn = connect_to_mysql(config)
        cursor = conn.cursor()
        cursor.execute("select name from teams order by name;")
        rows = cursor.fetchall()
        TeamList = list(chain.from_iterable(rows))
        conn.close()
        self.cb_selteam.addItems(TeamList)


    def loadteam(self):
        header = self.tbl_team.horizontalHeader()
        team = self.cb_selteam.currentText()
        # Connect to DB and load roster into combobox
        config = get_db_config()
        conn = connect_to_mysql(config)
        cursor = conn.cursor()
        qry = f"select jersey_no, name, posi, ht, wt, yrs, spd, rush, rcv,blk, pass, kick from active_players where team = '{team}' ;"
        #print(qry)
        cursor.execute(qry)
        rows = cursor.fetchall()
        self.tbl_team.setRowCount(len(rows))
        print (len(rows))
        i = 0
        for row in rows:
           j = 0
           for item in row:
              if j == 6:
                item = str(item)
              info = QTableWidgetItem()
              info.setData(Qt.EditRole,item)
              self.tbl_team.setItem(i,j,info)
              j += 1
           i += 1 
        header.setSectionResizeMode(0,QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(1,QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(2,QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(3,QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(4,QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(5,QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(6,QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(7,QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(8,QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(9,QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(10,QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(11,QtWidgets.QHeaderView.ResizeToContents)
            
        conn.close()
        

    def retranslateUi(self, view_roster):
        _translate = QtCore.QCoreApplication.translate
        view_roster.setWindowTitle(_translate("view_roster", "View Roster"))
        self.loadButton.setText(_translate("view_roster", "Load Team"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    view_roster = QtWidgets.QMainWindow()
    ui = Ui_view_roster()
    ui.setupUi(view_roster)
    view_roster.show()
    sys.exit(app.exec_())
